# Generated by Django 5.2.8 on 2025-11-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ПІБ')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
            ],
        ),
    ]
